const jobs = [
    {
        id: 1,
        title: "SDE Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "DSA", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹45k/month",
        applyUrl: "https://amazon.jobs",
        description: "Join Amazon as an SDE Intern. You will work on distributed systems and solve complex problems at scale. Strong DSA and problem-solving skills required."
    },
    {
        id: 2,
        title: "Frontend Developer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Redux", "TypeScript"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "12-18 LPA",
        applyUrl: "https://razorpay.com/jobs",
        description: "We are looking for a Frontend Developer to build seamless payment experiences. Proficiency in React and modern JS ecosystems is a must."
    },
    {
        id: 3,
        title: "Java Developer",
        company: "Infosys",
        location: "Pune",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "SQL"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "3.6-5 LPA",
        applyUrl: "https://infosys.com/careers",
        description: "Develop and maintain enterprise-grade Java applications. Knowledge of Spring Boot and REST APIs is essential."
    },
    {
        id: 4,
        title: "Data Analyst Intern",
        company: "Swiggy",
        location: "Remote",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Python", "SQL", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹25k/month",
        applyUrl: "https://swiggy.com/careers",
        description: "Analyze large datasets to drive business decisions. Proficiency in SQL and data visualization tools is preferred."
    },
    {
        id: 5,
        title: "Graduate Engineer Trainee",
        company: "TCS",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C++", "Java", "Communication"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "3.5-4.5 LPA",
        applyUrl: "https://tcs.com/careers",
        description: "Start your career with TCS as a GET. Training will be provided in various technologies based on business requirements."
    },
    {
        id: 6,
        title: "Backend Engineer",
        company: "CRED",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Go", "Microservices", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "18-25 LPA",
        applyUrl: "https://cred.club/careers",
        description: "Build high-performance backend systems at CRED. Experience with Go and distributed systems is highly valued."
    },
    {
        id: 7,
        title: "QA Engineer (Intern)",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Selenium", "Java", "Manual Testing"],
        source: "Zoho Careers",
        postedDaysAgo: 4,
        salaryRange: "₹15k/month",
        applyUrl: "https://zoho.com/careers",
        description: "Ensure software quality through manual and automated testing. Learn and grow with Zoho's engineering team."
    },
    {
        id: 8,
        title: "React Developer",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React Native", "Redux", "JavaScript"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "15-22 LPA",
        applyUrl: "https://flipkartcareers.com",
        description: "Work on Flipkart's mobile and web platforms. Deep understanding of React and performance optimization is required."
    },
    {
        id: 9,
        title: "Python Developer",
        company: "Accenture",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Python", "Django", "AWS"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "4.5-6.5 LPA",
        applyUrl: "https://accenture.com/careers",
        description: "Develop scalable Python applications. Experience with cloud platforms like AWS is a plus."
    },
    {
        id: 10,
        title: "Full Stack Developer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Remote",
        experience: "3-5",
        skills: ["Node.js", "Ember.js", "MySQL"],
        source: "Freshworks Careers",
        postedDaysAgo: 3,
        salaryRange: "20-30 LPA",
        applyUrl: "https://freshworks.com/careers",
        description: "Build full-stack solutions for Freshworks suite of products. Expertise in Node.js and frontend frameworks required."
    },
    {
        id: 11,
        title: "Software Engineer",
        company: "Microsoft",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["C#", ".NET", "Azure"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "14-16 LPA",
        applyUrl: "https://careers.microsoft.com",
        description: "Join Microsoft to empower every person/org. Solid CS fundamentals and coding skills required."
    },
    {
        id: 12,
        title: "DevOps Engineer",
        company: "Paytm",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Docker", "Kubernetes", "Jenkins"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "10-15 LPA",
        applyUrl: "https://paytm.com/careers",
        description: "Manage CI/CD pipelines and infrastructure scaling. Hands-on experience with Docker and Kubernetes is essential."
    },
    {
        id: 13,
        title: "Android Developer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Kotlin", "Java", "Android Studio"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "16-24 LPA",
        applyUrl: "https://phonepe.com/careers",
        description: "Build the next generation of payments apps. Proficiency in Kotlin and Android components is required."
    },
    {
        id: 14,
        title: "Business Analyst",
        company: "Deloitte",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["SQL", "Tableau", "Excel"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "6-8 LPA",
        applyUrl: "https://deloitte.com/careers",
        description: "Analyze business processes and provide data-driven insights. Strong analytical and communication skills needed."
    },
    {
        id: 15,
        title: "System Engineer",
        company: "Wipro",
        location: "Chennai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Linux", "Scripting", "Networking"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "3.5-4 LPA",
        applyUrl: "https://wipro.com/careers",
        description: "Maintain and troubleshooting system infrastructure. Knowledge of Linux and networking concepts is required."
    },
    {
        id: 16,
        title: "Product Designer",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Figma", "UI/UX", "Prototyping"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "12-18 LPA",
        applyUrl: "https://zomato.com/careers",
        description: "Design delightful user experiences for Zomato app. Portfolio demonstrating strong UI/UX skills is mandatory."
    },
    {
        id: 17,
        title: "Cloud Support Associate",
        company: "Amazon Web Services",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Linux", "Networking", "AWS"],
        source: "Amazon Jobs",
        postedDaysAgo: 3,
        salaryRange: "5-7 LPA",
        applyUrl: "https://amazon.jobs",
        description: "Provide technical support for AWS customers. Strong troubleshooting skills in Linux/Windows and networking."
    },
    {
        id: 18,
        title: "Associate Software Engineer",
        company: "Tech Mahindra",
        location: "Pune",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "SQL"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "3.25-4 LPA",
        applyUrl: "https://techmahindra.com",
        description: "Entry level software engineering role. Training provided. Basic coding knowledge required."
    },
    {
        id: 19,
        title: "Cyber Security Analyst",
        company: "IBM",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["SIEM", "Network Security", "Python"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "9-14 LPA",
        applyUrl: "https://ibm.com/careers",
        description: "Monitor and respond to security incidents. Experience with SIEM tools and threat analysis needed."
    },
    {
        id: 20,
        title: "Data Scientist",
        company: "Fractal Analytics",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "Machine Learning", "SQL"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "12-16 LPA",
        applyUrl: "https://fractal.ai/careers",
        description: "Build ML models to solve business problems. Strong statistical and programming background required."
    },
    {
        id: 21,
        title: "React Intern",
        company: "Groww",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["React", "HTML/CSS", "JS"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹30k/month",
        applyUrl: "https://groww.in/careers",
        description: "Internship opportunity for React enthusiasts. Work on high-scale investment platform frontend."
    },
    {
        id: 22,
        title: "iOS Developer",
        company: "Urban Company",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Swift", "iOS SDK", "Xcode"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "15-20 LPA",
        applyUrl: "https://urbancompany.com/careers",
        description: "Develop iOS applications for Urban Company. Proficiency in Swift and UI Kit/SwiftUI is expected."
    },
    {
        id: 23,
        title: "Technical Consultant",
        company: "Oracle",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["SQL", "PL/SQL", "Java"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "6-8 LPA",
        applyUrl: "https://oracle.com/careers",
        description: "Consulting role involving Oracle technologies. Good understanding of databases and SQL is required."
    },
    {
        id: 24,
        title: "Software Developer",
        company: "Zoho",
        location: "Tenkasi",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["C", "C++", "Java"],
        source: "Zoho Careers",
        postedDaysAgo: 2,
        salaryRange: "4-6 LPA",
        applyUrl: "https://zoho.com/careers",
        description: "Core product development role at Zoho. Strong problem solving and C/C++ skills are valued."
    },
    {
        id: 25,
        title: "Analyst",
        company: "Goldman Sachs",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "C++", "Finance"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "18-22 LPA",
        applyUrl: "https://goldmansachs.com/careers",
        description: "Join as an Analyst in Engineering. Top-tier coding skills and aptitude for finance required."
    },
    {
        id: 26,
        title: "Test Automation Engineer",
        company: "Capgemini",
        location: "Pune",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Selenium", "Java", "Cucumber"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "5-8 LPA",
        applyUrl: "https://capgemini.com/careers",
        description: "Automate test scenarios using Selenium. Experience with BDD frameworks like Cucumber is a plus."
    },
    {
        id: 27,
        title: "Developer Associate",
        company: "SAP",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Java", "Cloud", "ABAP"],
        source: "SAP Careers",
        postedDaysAgo: 3,
        salaryRange: "8-12 LPA",
        applyUrl: "https://sap.com/careers",
        description: "Develop enterprise software solutions. Exposure to cloud technologies and SAP ecosystem is beneficial."
    },
    {
        id: 28,
        title: "Product Manager Intern",
        company: "Meesho",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Analytics", "Strategy", "Communication"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹40k/month",
        applyUrl: "https://meesho.com/careers",
        description: "Assist PMs in driving product vision. Strong analytical mindset and user empathy required."
    },
    {
        id: 29,
        title: "Application Developer",
        company: "IBM",
        location: "Kolkata",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Java", "J2EE", "Spring"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "6-9 LPA",
        applyUrl: "https://ibm.com/careers",
        description: "Application development and maintenance. Expertise in Java stack is required."
    },
    {
        id: 30,
        title: "Site Reliability Engineer",
        company: "Jio",
        location: "Mumbai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Linux", "Python", "Monitoring"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "10-15 LPA",
        applyUrl: "https://jio.com/careers",
        description: "Ensure high availability of Jio platforms. Scripting and monitoring tool experience needed."
    }
];

// Replicating/Randomizing slightly to get to 60 without writing all unique manually for this demo
const moreJobs = jobs.map(job => ({
    ...job,
    id: job.id + 30,
    title: job.title.includes("Intern") ? job.title.replace("Intern", "II") : job.title + " (Senior)",
    postedDaysAgo: Math.floor(Math.random() * 10),
    department: "Engineering" // dummy field
})).slice(0, 30); // Taking 30 more

const allJobs = [...jobs, ...moreJobs];

// Export logic for browser (window object)
window.jobData = allJobs;
